---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/pzmvqbvj/public_html/
    - /bin/cp assets $DEPLOYPATH
    - /bin/cp backend $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
